exo/config/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.conf import settings

urlpatterns = [
    url(settings.ADMIN_URL, admin.site.urls),
    url(r'^u/', include('studio.users.urls', namespace='user')),
    url(r'^', include('studio.figures.urls', namespace='models')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

exo/studio/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from django.contrib.auth.views import (
    logout_then_login, login,
    password_change
)
from django.core.urlresolvers import reverse_lazy
from django.views import generic

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=generic.RedirectView.as_view(
            url=reverse_lazy('user:redirect')
        ),
        name='index'
    ),
    url(
        regex='^login/$',
        view=login,
        kwargs={'template_name': 'login.html'},
        name='login'
    ),
    url(
        regex=r'^change-password/$',
        view=password_change,
        kwargs={
            'post_change_redirect': reverse_lazy('user:logout'),
            'template_name': 'password_change_form.html'
        },
        name='change-password'
    ),
    url(
        regex=r'^add/$',
        view=views.UserDesignerCreateAccount.as_view(),
        name='create'
    ),
    url(
        regex=r'^redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<pk>\d+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^(?P<pk>\d+)/change/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex='^model-list/$',
        view=views.DesignerListModelView.as_view(),
        name='model-list'
    ),
    url(
        regex='^model-list/add/$',
        view=views.DesignerAddModelView.as_view(),
        name='add-model'
    ),
    url(
        regex='^model-list/(?P<uid>[a-f,0-9]+)/$',
        view=views.DesignerModelDetailView.as_view(),
        name='model-detail'
    ),
    url(
        regex='^model-list/(?P<uid>[a-f,0-9]+)/change/$',
        view=views.DesignerChangeModelView.as_view(),
        name='model-change'
    ),
    url(
        regex='^logout/$',
        view=logout_then_login,
        name='logout'
    ),
]

exo/studio/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.utils.functional import cached_property
from django.core.urlresolvers import reverse_lazy
from django.conf import settings
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices

try:
    from badges.models import Badge
except ImportError:
    Badge = None


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    gender = models.CharField(
        _('Gender'),
        max_length=4,
        choices=Choices(*settings.USER_GENDERS),
    )

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse_lazy('user:detail', kwargs={'pk': self.pk})

    def get_full_name(self):
        ret = super().get_full_name()
        return '{} {}'.format(self.gender, ret or self.name)

    def get_short_name(self):
        ret = super().get_short_name()
        return ret or self.name

    @cached_property
    def badges(self):
        if Badge is None:
            return []
        return Badge.objects.filter(user=self)

exo/studio/users/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth.models import Group
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class DesignerCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('gender', 'username', 'name')

    def save(self, commit=True):
        obj = super().save(commit)
        group, _ = Group.objects.get_or_create(name=settings.DESIGNER_GROUP_NAME)
        obj.groups.add(group)
        return obj


class DesignerChangeForm(UserChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('gender', 'name', 'password', )

exo/studio/users/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from django.contrib.auth import get_user_model

from studio.helpers.mixins import DesignerGroupMixin
from studio.figures.models import Model3D
from studio.figures.forms import AddModel3DForm, ChangeModel3DForm
from .forms import DesignerChangeForm, DesignerCreationForm

# Create your views here.


@method_decorator(login_required, name='dispatch')
class UserRedirectView(DesignerGroupMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse('user:detail', args=[self.request.user.pk])


class UserDesignerCreateAccount(generic.CreateView):
    model = get_user_model()
    form_class = DesignerCreationForm
    template_name = 'add_designer.html'

    def get_success_url(self):
        return reverse('user:login')


@method_decorator(login_required, name='dispatch')
class UserDetailView(DesignerGroupMixin, generic.DetailView):
    model = get_user_model()
    template_name = 'designer_details.html'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(pk=self.request.user.pk)
        return qs


@method_decorator(login_required, name='dispatch')
class UserUpdateView(DesignerGroupMixin, generic.UpdateView):
    model = get_user_model()
    form_class = DesignerChangeForm
    template_name = 'change_designer.html'

    def get_success_url(self):
        return reverse('user:detail', args=[self.request.user.pk])

    def get_initial(self):
        initial = super().get_initial()
        initial.update({'request': self.request})
        return initial

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(pk=self.request.user.pk)
        return qs


@method_decorator(login_required, name='dispatch')
class DesignerListModelView(DesignerGroupMixin, generic.ListView):
    model = Model3D
    template_name = 'designer_model_list.html'
    context_object_name = 'items'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(designer=self.request.user)


@method_decorator(login_required, name='dispatch')
class DesignerAddModelView(DesignerGroupMixin, generic.CreateView):
    model = Model3D
    template_name = 'designer_add_model.html'
    form_class = AddModel3DForm

    def get_success_url(self):
        return reverse('user:model-list')

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


@method_decorator(login_required, name='dispatch')
class DesignerChangeModelView(DesignerGroupMixin, generic.UpdateView):
    model = Model3D
    template_name = 'designer_change_model.html'
    slug_url_kwarg = 'uid'
    slug_field = 'uid'
    form_class = ChangeModel3DForm

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(designer=self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def get_success_url(self):
        return reverse('user:model-list')


@method_decorator(login_required, name='dispatch')
class DesignerModelDetailView(DesignerGroupMixin, generic.DetailView):
    model = Model3D
    template_name = 'designer_model_details.html'
    slug_url_kwarg = 'uid'
    slug_field = 'uid'

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(designer=self.request.user)
        return qs

exo/studio/users/templates/add_designer.html
{% load i18n %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">{% trans 'Create' %}</button>
</form>

exo/studio/users/templates/change_designer.html
{% load i18n %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>

exo/studio/users/templates/designer_add_model.html
{% load i18n %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">{% trans 'Add' %}</button>
</form>

exo/studio/users/templates/designer_change_model.html
{% load i18n %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">{% trans 'Save' %}</button>
</form>

exo/studio/users/templates/designer_details.html
{% load i18n %}

{% trans 'Your fullname' %}: {{ object.get_full_name }}
<div>
    <a href="{% url 'user:update' user.pk %}">{% trans 'Change profile' %}</a>
    <a href="{% url 'user:change-password' %}">{% trans 'Change password' %}</a>
</div>

<br>

<div>
    {% trans 'Your badge list' %}:
    <ul>
        {% for badge in object.badges.all %}
            <li>
                <b>{{ badge.title }}</b>
            </li>
        {% empty %}
            <li>{% trans 'No badges found' %}</li>
        {% endfor %}
    </ul>
</div>


<div>
    <a href="{% url 'user:model-list' %}">{% trans 'List models' %}</a> | <a href="{% url 'user:add-model' %}">{% trans 'Add model' %}</a>
</div>


<div>
    <a href="{% url 'user:logout' %}">{% trans 'Logout' %}</a>
</div>

exo/studio/users/templates/designer_model_details.html
{% load i18n %}

{% trans 'Name' %}: {{ object.name }} <br>
{% trans 'UID' %}: {{ object.uid.hex }} <br>
{% trans 'Views counter' %}: {{ object.view_counter }}<br>

{% trans "Evaluations" %}
{# L'ideal serait de charger les commentaires via une vue ajax #}
{% for item in object.evaluation_set.all %}
    <p>
        <span>{% trans "Email" %}: {{ item.commentator }}</span>
        <span>{% trans "Comment" %}: {{ item.comment }}</span>
        <span>{% trans "Rating" %}: {{ item.evaluation }}</span>
    </p>
{% empty %}
    <p>{% trans 'No evaluation report' %}</p>
{% endfor %}
<br>
<a href="..">{% trans 'Back' %}</a> | <a href="{% url 'user:model-change' object.uid.hex %}">{% trans "Change" %}</a>

exo/studio/users/templates/designer_model_list.html
{% load i18n %}
<ul>
    {% for item in items %}
        <li>
            <a href="{% url 'user:model-detail' item.uid.hex %}">{{ item.name }}</a> |
            {% trans 'Active' %} <i>{% if item.is_active %}Yes{% else %}No{% endif %}</i>
        </li>
    {% empty %}
        <li>{% trans 'No model found' %}</li>
    {% endfor %}
</ul>

<div>
    <a href="..">{% trans 'Back' %}</a>
    <a href="{% url 'user:add-model' %}">{% trans 'Add model' %}</a>
</div>

exo/studio/users/templates/login.html
{% load i18n %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">{% trans 'Sign up' %}</button>
</form>
<br>
<a href="{% url 'user:create' %}">{% trans "Create account" %}</a>

exo/studio/users/templates/password_change_form.html
{% load i18n %}

<form action="" method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <button type="submit">{% trans 'Confirm' %}</button>
</form>